[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:.*asyncio.get_event_loop_policy.*:DeprecationWarning:pytest_asyncio\.plugin
    ignore:.*asyncio.set_event_loop_policy.*:DeprecationWarning:pytest_asyncio\.plugin
    ignore:.*asyncio.DefaultEventLoopPolicy.*:DeprecationWarning:aiohttp\.pytest_plugin
    ignore:.*asyncio.iscoroutinefunction.*:DeprecationWarning:aiohttp\.
